#!/bin/sh
# Record every tool version this project actually depends on.
#
# versions.env pins the handful of tools we CHOOSE. This records what we GOT --
# including the ~dozen pinned transitively by the container image tag, which we
# do not choose and must not hand-maintain. Run inside the container; the output
# is committed so a version change shows up as a reviewable diff.
#
# Regenerate with `make tool-manifest`. Never hand-edit the output.
#
# This script READS. It never edits versions.env or requirements.txt, nothing
# depends on it, and no target or CI job runs it for you. Bumping a pin stays a
# deliberate human act; this only tells you what you are currently running.

set -eu

ver() {
	name=$1
	shift
	if command -v "$1" >/dev/null 2>&1; then
		out=$("$@" 2>&1 | head -1 | tr -s ' ' | sed 's/^ *//;s/ *$//')
		printf '%-12s %s\n' "$name" "${out:-<no version output>}"
	else
		printf '%-12s ABSENT\n' "$name"
	fi
}

printf '# Tool manifest -- generated by make tool-manifest. Do not hand-edit.\n#\n'
printf '# Pinned inputs (versions.env): image tag %s\n' "${OSIC_TOOLS_TAG:-<unset>}"
printf '# Everything else below is pinned transitively BY that tag.\n\n'

printf '## Environment\n'
printf '%-12s %s\n' "image" "hpretl/iic-osic-tools:${OSIC_TOOLS_TAG:-<unset>}"
printf '%-12s %s\n' "PDK" "${PDK:-<unset>}"
printf '%-12s %s\n' "PDK_ROOT" "${PDK_ROOT:-<unset>}"

# The PDK is not separately pinnable: open_pdks is built into the image, and
# $PDK_ROOT/sky130A/SOURCES records the exact commit it was built from. That
# hash IS the PDK version, fixed transitively by the image tag.
# (Do not confuse it with $PDK_ROOT/versions.txt, which records the tool
# versions used at PDK BUILD time and does not track what is installed now.)
if [ -r "${PDK_ROOT:-/nonexistent}/${PDK:-sky130A}/SOURCES" ]; then
	printf '%-12s %s\n\n' "open_pdks" \
		"$(awk '/open_pdks/ {print $2; exit}' "${PDK_ROOT}/${PDK}/SOURCES")"
else
	printf '%-12s %s\n\n' "open_pdks" "<no SOURCES file>"
fi

printf '## Digital (pinned in versions.env, enforced by make check-tools)\n'
ver verilator verilator --version
ver yosys yosys -V
ver verible verible-verilog-format --version
printf '\n'

# GTKWave and surfer are GUI viewers: they cannot report a version without a
# display, and their version cannot change a result. Deliberately not recorded.
printf '## Digital (from the image)\n'
ver iverilog iverilog -V
printf '\n'

printf '## Analog and physical (from the image)\n'
ver magic magic --version
ver netgen netgen -batch quit
ver klayout klayout -v
# ngspice leads with a banner line; the version is on the line naming it.
if command -v ngspice >/dev/null 2>&1; then
	printf '%-12s %s\n' "ngspice" \
		"$(ngspice --version 2>&1 | grep -m1 -o 'ngspice-[0-9.]*' || echo '<unparsed>')"
else
	printf '%-12s ABSENT\n' "ngspice"
fi
ver xschem xschem --version
printf '\n'

printf '## Python (pinned in requirements.txt, enforced by pip)\n'
ver python python --version
for pkg in cocotb pytest numpy ruff; do
	if python -c "import importlib.metadata as m; m.version('$pkg')" >/dev/null 2>&1; then
		printf '%-12s %s\n' "$pkg" "$(python -c "import importlib.metadata as m; print(m.version('$pkg'))")"
	else
		printf '%-12s ABSENT\n' "$pkg"
	fi
done
