"""Inverter sweeps and Monte Carlo, driven from the generated netlist.

The schematic is netlisted once and then treated as a template: this script
lifts the cell's subcircuit out of it, restamps the device geometry, and hands
a generated deck to ngspice. inv.sch is never opened. Rewriting the schematic to
change a width means a crashed run leaves a half-edited cell on disk, and the
schematic stays the single source of truth for topology either way.

Cost is dominated by one thing. Parsing the sky130 model library takes about
45 s -- an `op` on a bare resistor with that .lib costs the same -- while the
sweep itself is free. So the unit of work is the ngspice *process*, not the
simulation, and both commands here are built to pay that toll once:

  sweep   every geometry is instantiated as its own subcircuit in one deck,
          sharing one input source, and read out on its own output node.
          One DC sweep, one parse, N results.
  mc      draws are a dowhile around `reset`, which is what re-evaluates the
          AGAUSS mismatch terms without reloading the library.

W and L are written as instance parameters on the subcircuit call, which is what
Monte Carlo requires. The mismatch terms are AGAUSS expressions evaluated inside
the PDK's wrapper against the w and l it was called with. Reaching past the
wrapper to alter the inner MOSFET's width would leave those terms sized for the
original geometry, so sigma would hold still while the geometry moved -- a
Pelgrom check that cannot fail, and therefore cannot pass.
"""

from __future__ import annotations

import argparse
import csv
import itertools
import os
import pathlib
import re
import statistics
import subprocess
import sys

HERE = pathlib.Path(__file__).parent
NETLIST = HERE / "simulation" / "tb_inv.spice"

DEVICE = re.compile(
    r"^(?P<head>X\S+(?:\s+\S+){4}\s+sky130_fd_pr__(?P<flavour>[np])fet_01v8)\s.*$",
    re.M,
)
SUBCKT = re.compile(r"^\.subckt\s+inv\b.*?^\.ends\s*$", re.M | re.S)
LIB = re.compile(r"^\.lib\s+(\S*sky130\.lib\.spice)\s+\w+\s*$", re.M)

# ngspice opens every meas result with "name = value" at the start of a line.
# Keying on the full name is what keeps gain_at_vm from being read as vm, and
# the line is not end-anchored because a min/max measurement trails an "at=".
RESULT = re.compile(r"^\s*(\w+)\s*=\s*([-+\d.eE]+)", re.M)

VDD = 1.8
CLOAD = "10f"


class Point:
    """One geometry, and the node it is measured on."""

    def __init__(self, index: int, wn: float, wp: float, length: float, mult: int = 1):
        self.index = index
        self.wn = wn
        self.wp = wp
        self.length = length
        self.mult = mult
        self.cell = f"cell{index}"
        self.node = f"out{index}"


def device_line(head: str, w: float, length: float, mult: int = 1, nf: int = 1) -> str:
    """Restamp a device line, deriving junction geometry from W as the symbol does.

    ad/as/pd/ps are the sky130 symbol's own expressions, evaluated here so a
    resized device does not carry the previous width's junction areas into a
    transient run.
    """
    ad = int((nf + 1) / 2) * w / nf * 0.29
    pd = 2 * int((nf + 1) / 2) * (w / nf + 0.29)
    area_s = int((nf + 2) / 2) * w / nf * 0.29
    ps = 2 * int((nf + 2) / 2) * (w / nf + 0.29)
    nr = 0.29 / w
    return (
        f"{head} L={length:g} W={w:g} nf={nf} ad={ad:g} as={area_s:g} "
        f"pd={pd:g} ps={ps:g} nrd={nr:g} nrs={nr:g} sa=0 sb=0 sd=0 mult={mult:g}"
    )


class Template:
    """The netlist as a parts bin: the model library, and the cell's subcircuit."""

    def __init__(self, path: pathlib.Path = NETLIST):
        text = path.read_text()
        lib = LIB.search(text)
        cell = SUBCKT.search(text)
        if not lib or not cell:
            sys.exit(f"{path} has no .lib line or no `inv` subcircuit -- re-netlist it")
        self.lib_path = lib.group(1)
        self.cell = cell.group(0)

    def sized(self, point: Point) -> str:
        def swap(m: re.Match) -> str:
            is_n = m.group("flavour") == "n"
            w = point.wn if is_n else point.wp
            return device_line(m.group("head"), w, point.length, point.mult)

        body = DEVICE.sub(swap, self.cell)
        return re.sub(r"^\.subckt\s+inv\b", f".subckt {point.cell}", body, flags=re.M)

    def deck(self, points: list[Point], corner: str, mismatch: bool, control: str) -> str:
        lines = [
            "* generated by characterize.py",
            f".lib {self.lib_path} {corner}",
            f".param mc_mm_switch={int(mismatch)}",
            ".param mc_pr_switch=0",
            "",
            *(self.sized(p) for p in points),
            "",
            f"VDD vdd 0 {VDD}",
            "VIN in 0 dc 0",
        ]
        for p in points:
            lines.append(f"X{p.index} vdd {p.node} in 0 {p.cell}")
            lines.append(f"C{p.index} {p.node} 0 {CLOAD}")
        lines += ["", control, ".end", ""]
        return "\n".join(lines)


def ngspice(deck: str) -> dict[str, list[float]]:
    """Run one deck and collect every measurement it printed, in order.

    ngspice's exit status does not distinguish a converged run from a deck that
    parsed and produced nothing, so a missing measurement is the failure signal.
    """
    # Unique per process: two concurrent runs sharing one scratch deck would
    # silently simulate each other's geometry.
    scratch = NETLIST.with_name(f"_run{os.getpid()}.spice")
    scratch.write_text(deck)
    proc = subprocess.run(
        ["ngspice", "-b", scratch.name],
        cwd=scratch.parent,
        capture_output=True,
        text=True,
    )
    results: dict[str, list[float]] = {}
    for name, value in RESULT.findall(proc.stdout):
        results.setdefault(name, []).append(float(value))
    scratch.unlink(missing_ok=True)
    if not results:
        sys.exit(f"ngspice produced no measurements\n{proc.stdout}\n{proc.stderr}")
    return results


def vtc_control(points: list[Point], temp: float) -> str:
    lines = [".control", "set nomodcheck"]
    if temp != 27:
        lines.append(f"option temp = {temp:g}")
    lines.append(f"dc VIN 0 {VDD} 0.005")
    for p in points:
        i = p.index
        lines += [
            f"let diff{i} = v({p.node}) - v(in)",
            f"meas dc vm{i} when diff{i}=0",
            f"let slope{i} = deriv(v({p.node}))",
            f"meas dc gain{i} find slope{i} when diff{i}=0",
            f"meas dc peak{i} min slope{i}",
        ]
    lines.append(".endc")
    return "\n".join(lines)


def mc_control(points: list[Point], runs: int) -> str:
    body = [".control", "set nomodcheck", "let k = 0", f"dowhile k < {runs}", "  reset",
            f"  dc VIN 0 {VDD} 0.005"]
    for p in points:
        i = p.index
        body += [
            f"  let diff{i} = v({p.node}) - v(in)",
            f"  meas dc vm{i} when diff{i}=0",
        ]
    body += ["  let k = k + 1", "end", ".endc"]
    return "\n".join(body)


def cmd_sweep(args: argparse.Namespace) -> None:
    template = Template()
    points = [
        Point(i, args.wn, args.wn * ratio, length)
        for i, (length, ratio) in enumerate(itertools.product(args.lengths, args.ratios))
    ]
    got = ngspice(template.deck(points, args.corner, False, vtc_control(points, args.temp)))

    rows = []
    for p in points:
        i = p.index
        rows.append(
            {
                "wn": p.wn,
                "wp": p.wp,
                "mult": p.mult,
                "l": p.length,
                "ratio": p.wp / p.wn,
                "corner": args.corner,
                "temp": args.temp,
                "vm": got[f"vm{i}"][0],
                "gain_at_vm": got[f"gain{i}"][0],
                "peak_gain": got[f"peak{i}"][0],
            }
        )
        print(
            f"L={p.length:<5g} Wp/Wn={p.wp / p.wn:<5g} "
            f"vm={rows[-1]['vm']:.4f}  gain={rows[-1]['gain_at_vm']:.2f}"
        )

    with open(args.out, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    print(f"\n{len(rows)} points -> {args.out}")


def cmd_mc(args: argparse.Namespace) -> None:
    template = Template()
    # The Pelgrom leg scales mult, not W. The PDK spends its mismatch as
    # slope/sqrt(l*w*mult), so all three raise area equally -- but W and L also
    # move the operating point, and a sigma measured at a different Vm is not
    # the same measurement. Replicating the device leaves current density, Vm
    # and every bias untouched, which is the only leg that isolates area.
    points = [Point(0, args.wn, args.wn * args.ratio, args.l)]
    if args.pelgrom > 1:
        points.append(Point(1, args.wn, args.wn * args.ratio, args.l, int(args.pelgrom)))

    got = ngspice(template.deck(points, args.corner, True, mc_control(points, args.runs)))

    sigmas = []
    with open(args.out, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["wn", "wp", "l", "mult", "corner", "vm"])
        for p in points:
            draws = got[f"vm{p.index}"]
            if len(draws) != args.runs:
                sys.exit(f"expected {args.runs} draws, parsed {len(draws)}")
            sigma = statistics.pstdev(draws)
            sigmas.append(sigma)
            print(
                f"Wn={p.wn:g} Wp={p.wp:g} L={p.length:g} mult={p.mult}  n={len(draws)}  "
                f"mean={statistics.fmean(draws) * 1e3:.2f} mV  sigma={sigma * 1e3:.3f} mV"
            )
            for v in draws:
                writer.writerow([p.wn, p.wp, p.length, p.mult, args.corner, v])

    if len(sigmas) == 2:
        print(
            f"\nsigma ratio {sigmas[0] / sigmas[1]:.3f}  "
            f"(Pelgrom predicts {args.pelgrom ** 0.5:.3f})"
        )
    print(f"draws -> {args.out}")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    sub = p.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("sweep", help="Vm and gain over Wp/Wn and L")
    s.add_argument("--wn", type=float, default=1.0)
    s.add_argument("--ratios", type=float, nargs="+", default=[1, 1.5, 2, 3, 4])
    s.add_argument("--lengths", type=float, nargs="+", default=[0.15, 0.3, 0.5, 1.0])
    s.add_argument("--corner", default="tt")
    s.add_argument("--temp", type=float, default=27)
    s.add_argument("--out", default=HERE / "simulation" / "sweep.csv")
    s.set_defaults(func=cmd_sweep)

    m = sub.add_parser("mc", help="spread of Vm under device mismatch")
    m.add_argument("--wn", type=float, default=1.0)
    m.add_argument("--ratio", type=float, default=4.0)
    m.add_argument("--l", type=float, default=0.15)
    m.add_argument("--runs", type=int, default=200)
    m.add_argument("--corner", default="tt")
    m.add_argument("--pelgrom", type=float, default=1.0,
                   help="repeat with mult scaled by this factor; sigma should fall by its root")
    m.add_argument("--out", default=HERE / "simulation" / "mc_vm.csv")
    m.set_defaults(func=cmd_mc)

    args = p.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
